redirects:
  security/smart-contract-audits: security/audits.md
  governance/eul: eul/distribution.md
  developers/integration-guide: developers/getting-started.md
  governance/grants: euler-governance/grants.md
