name: Check Markdown links
'on':
  pull_request:
    branches:
      - master
jobs:
  markdown-link-check:
    name: Check Links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gaurav-nelson/github-action-markdown-link-check@95ffb9cc0e73598e4c8b38ededb26fb209801877 # pin v1.0.13
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          config-file: .md-link-check.json
